spring:
  application:
    name: user-micro-service
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${USER_SERVICE_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user-service-db}
    username: ${USER_SERVICE_DATASOURCE_USERNAME:postgres}
    password: ${USER_SERVICE_DATASOURCE_PASSWORD:postgres}
    hikari:
      auto-commit: true
      schema: app
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    schemas: app
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true  # ← Запретить clean в продакшене
    out-of-order: false
    create-schemas: true
server:
  port: 8081